# Generated by Django 3.0.7 on 2020-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=7)),
            ],
        ),
    ]
