# Generated by Django 3.0.7 on 2020-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='altphone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
