# Generated by Django 3.0.7 on 2020-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
